name: .NET Core CI
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: .NET Build
        run: dotnet build 
        working-directory: docfx-documentation
      - name: .NET Test
        id: dotnet_test
        run: |
            dotnet test --collect:"XPlat Code Coverage"
            REPORT_PATH=`find ./ -name "coverage*.xml"`
            echo ::set-output name=report_path::${REPORT_PATH}
        working-directory: docfx-documentation
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: docfx-documentation/${{ steps.dotnet_test.outputs.report_path }}